About page
jvmontes/lpdd pull request #14
Opened 2024-09-30 22:54 UTC by fgonza23

About page 
about.css

2024-10-01 03:39 UTC, jvmontes requested changes
A couple of comments, I can start an implementation using Tailwind as an example but ideally we should just use straight up Tailwind for these components and not need a CSS file. Happy to work through this with you.

2024-10-01 03:39 UTC, jvmontes commented on public/profilepics/Frame 69.svg
This is not a profile picture. It should probably live under `src/app/ui/icons`

2024-10-01 03:39 UTC, jvmontes commented on public/profilepics/Frame 98.jpg
All of these images should ideally be renamed to something inline with what their content is about. So this one could be renamed to `gerardo-headshot.jpg`. Also for standard folder naming convention, the folder should be named `profile-pics` or better yet, `team-headshots`.

2024-10-01 03:39 UTC, jvmontes commented on src/app/ui/styles/about.css
> +    border-radius: 10px; /* Adjust as needed */
I see you got this from ChatGPT, huh? 😉  We should try to reduce the number of comments in our code. our code should be self-documenting, aka the code should do its best to tell you exactly what it's doing.

2024-10-01 03:39 UTC, jvmontes commented on src/app/ui/styles/about.css
> +    grid-template-columns: repeat(3, 350px); /* 3 columns */
This current implementation doesn't work for mobile. For each change, we should make sure mobile view is supported, since people will likely be visiting the website on a mobile device. There are ways we can account for this using Tailwind CSS. Basically, we add classes that fit for mobile views by default, then we add media queries to accommodate for larger views. On mobile, this would probably have 1 grid column, so we just show each item in line as the user scrolls. But then, once we get to an iPad, we want to do 3 columns. Figuring out iPhones in landscape might be tricky for this use case, might need to do 2 columns for that size, but would need to look into it and play around with it. To view the app on a mobile screen size, you can open your developer tools and there's a button to Toggle device toolbar. Let's make sure we fix this & implement using Tailwind before we merge.

2024-10-01 03:40 UTC, jvmontes commented on public/profilepics/Frame 69.svg
And should probably be renamed to something like `linkedin-icon.svg`

2024-10-01 03:51 UTC, jvmontes commented on src/app/about/page.tsx
> +            <img src={member.image} alt={member.name} className="team-member-image" />
From the ESLinter:

>Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-elementeslint[@next/next/no-img-element](https://nextjs.org/docs/messages/no-img-element)

2024-10-01 03:52 UTC, jvmontes commented
Also, make sure you setup your workspace to run the Prettier code formatter. I saved on my machine and it made some formatting updates. I'll make a separate commit now.

2024-10-03 17:45 UTC, fgonza23 commented
Closing this pull request as it is outdated. Creating a new one for the latest changes.

2024-10-03 17:47 UTC, closed without merging