About
jvmontes/lpdd pull request #16
Opened 2024-10-03 18:17 UTC by fgonza23

Updated About Page Design
Implemented Tailwind CSS for styling the About page, improving layout consistency and responsiveness.
Adjusted the team member section layout, including aligned images, text, and LinkedIn icons for better visual presentation.
Optimized the image and text alignment to match design requirements
Integrated custom CSS variables for consistent theme colors
Cleaned up redundant or outdated CSS in the project.

Resolved conflicts in src/app/globals.css and tailwind.config.ts.
Ensured all changes from the main branch were incorporated without affecting new updates on the About page.

2024-10-03 19:15 UTC, jvmontes requested changes
Looking good! A couple of requests for changes.

2024-10-03 19:15 UTC, jvmontes commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.2.2",
it looks like we're not using either of these libraries. Let's `npm uninstall` them.

2024-10-03 19:15 UTC, jvmontes commented on package.json
> +    "@svgr/webpack": "^8.1.0",
If we're not using this, let's remove this dev dependency.

2024-10-03 19:15 UTC, jvmontes commented on package.json
> +    "autoprefixer": "^10.4.20",
Are we using this autoprefixer anywhere? If not, let's remove it.

2024-10-03 19:15 UTC, jvmontes commented on src/app/ui/icons/linkedin-icon.svg
looks like we have the linkedin icon in two places. here, and in public. i think we can go ahead and delete the one in public.

2024-10-03 19:15 UTC, jvmontes commented on tailwind.config.ts
> +    "./src/app/about/**/*.{js,ts,jsx,tsx,mdx}",
I'm not 100% sure about this, but I believe you don't need this line, because the line above it should also include everything in `/about`.

2024-10-03 19:15 UTC, jvmontes commented on src/app/about/page.tsx
> +          <div key={index} className="flex w-64 flex-col items-center">
This isn't a necessary change for this PR, but something to consider that could help make more modular components would be to put this into its own component called TeamMemberCard or something. Again, not a necessary change for this PR, especially since this file is just at 104 lines of code. My rule of thumb is to keep any file under 100 lines of code if possible.

2024-10-10 12:09 UTC, galenom commented
Looks great! I noticed a styling issue with the images grid. The images look great on small and desktop screens. In between it looks like they aren't centered on the grid so might just need some additional breakpoint style or something. I attached some pictures to help. 

Not a blocker for this PR though. 

<img width="1000" alt="Screenshot 2024-10-10 at 7 49 22 AM" src="https://github.com/user-attachments/assets/3f5459fa-6cef-4013-8a90-8e8889c8b15b">
<img width="828" alt="Screenshot 2024-10-10 at 7 49 15 AM" src="https://github.com/user-attachments/assets/127b2d26-772a-4ba7-8c3b-67511cc3cde5">

2024-10-10 12:10 UTC, galenom approved these changes

2024-10-15 21:02 UTC, galenom approved these changes

2024-10-15 22:44 UTC, jvmontes approved these changes
Looks good! Ready to merge.

2024-10-15 22:44 UTC, jvmontes commented on src/app/about/page.tsx
> +        className="absolute inset-0 -z-10 bg-no-repeat"
We could talk to the designers about the custom background-art for this page and if it makes sense to reuse potentially on a different page, we could extract it to a custom BackgroundArt component.

2024-10-15 22:49 UTC, jvmontes commented
Ready to merge! 

@galenom I created a ticket for your point about the items not being centered in the grid and assigned it to @geraxrodriguez . Asana link here: https://app.asana.com/0/1207992233793749/1208554811111884/f

2024-10-15 22:50 UTC, merged