feat: add seed functionality for our database data
jvmontes/lpdd pull request #2
Opened 2024-08-16 18:14 UTC by galenom

Ticket: https://app.asana.com/0/1207992233793749/1208069710371317/f

This seed functionality is run outside of the next.js application. Running the seed script will allow us to use the same data across our different developer environments.

It's an initial implementation and needs further work.

TODO:
- Add contacts and events examples
- Prevent over-seeding. currently continues to add rows even if the data exists.

2024-08-17 20:17 UTC, jvmontes requested changes
Looks good!! A couple changes to think through.

2024-08-17 20:17 UTC, jvmontes commented on drizzle/seed-data.ts
> +export const techqueria_org = {
Ultimately feels like we would put this behind a form that org-admins can submit to add/edit/delete orgs.

2024-08-17 20:17 UTC, jvmontes commented on drizzle/seed-data.ts
> +  industry: '',
definitely think we should maybe keep an industry categories table. might be better than simply creating a text[]. Could also assist in indexing for searches.

2024-08-17 20:17 UTC, jvmontes commented on drizzle/seed-data.ts
> +  region: '',
for alpha version, we'll do 1 region, Chicagoland, and at least two cities: Chicago, and Joliet. Actually, maybe we could do another region for you, Mario? Idk if there's anything you know of locally. Definitely thinking on how we can make this easily accessible/indexable for searches as we scale. For now, I don't anticipate us adding too many regions, but if we start to grow, we will definitely have to be mindful of how we do this. Maybe it also makes sense to add a column for State, as well. Country, Zip Code, and County are all on the table for consideration, as well. Simply because it'll give us additional flexibility to refine searches as we scale.

2024-08-17 20:17 UTC, jvmontes commented on drizzle/seed-data.ts
> +  region: '',
Another additional thought, Techqueria as an organization has different chapters. Chicago, LA, San Diego, Denver, NYC, Miami, etc...... and other orgs may have various local chapters, as well.

2024-08-19 16:25 UTC, galenom commented on drizzle/seed-data.ts
> +  industry: '',
Make an `Industries` enum and have a 1-to-many relation to `Organizations` via `OrganizationIndustries`

2024-09-09 14:10 UTC, closed without merging