Directory
jvmontes/lpdd pull request #7
Opened 2024-09-12 04:24 UTC by jvmontes

- Add styled directory component with functional filter. 
- Add 3 orgs to mock directory data: ALPFA, Techqueria, and 1871. 
- Create Industry enum 

- Tested to make sure width of directory component doesn't change when items are filtered / unfiltered. 
- Tested to make sure height of directory doesn't decrease if there's less than 3 items displayed.
- Tested on mobile and desktop screens

Known issues:
- remove "X" when dropdown isn't open
- update styling to better reflect comps dropdown / filter button UI
- doesn't display selected industries anywhere when dropdown is closed
- no empty state for directory. Ideally, we should have at least 1 option for each possible combination of filters. I added Cybersecurity and Real Estate as industries, but don't have Raices Cyber nor NAHREP added, which would apply to each industry. 
- DirectoryOrg displays industry_tag spans, ideally we turn these into nice little chips for enhanced UI.
- Affinity enum isn't built out, but I wanted to place the idea. Something similar would be necessary for Locations (Chapters)
- Need unit tests to test Filter functionality with some mock data.

2024-09-16 23:17 UTC, geraxrodriguez commented on src/app/ui/filter.tsx
> +            <span>{industry}</span>
I believe text is supposed to be black is currently showing up as white, same as background.

2024-09-17 14:54 UTC, geraxrodriguez requested changes
Really great work man. I learned a lot going through this. All I have for you is that text-color comment!

2024-09-19 14:46 UTC, geraxrodriguez approved these changes
Looks good!

2024-09-22 03:52 UTC, geraxrodriguez commented on src/app/ui/filter.tsx
> +              stroke-linecap="round"
Noticed an error in console: "Invalid DOM property stroke-width. Did you mean strokeWidth?".
Same thing for stroke-linecap. Changing to both to camelCase fixes error.

2024-09-22 03:53 UTC, geraxrodriguez commented on src/app/ui/filter.tsx
> +              stroke-width="4"
strokeWidth

2024-09-22 03:55 UTC, geraxrodriguez commented on src/app/ui/filter.tsx
> +              stroke-width="3"
```suggestion
              strokeWidth="3"
```

2024-09-22 03:57 UTC, geraxrodriguez commented on src/app/ui/filter.tsx
> +              stroke-linecap="round"
```suggestion
              strokeLinecap="round"
```

2024-09-22 03:57 UTC, geraxrodriguez commented on src/app/ui/filter.tsx
> +              stroke-width="4"
```suggestion
              strokeWidth="4"
```

2024-09-23 02:35 UTC, geraxrodriguez commented on src/app/ui/directory.tsx
> +    <section className="flex flex-col items-center justify-between pt-8">
Looks like removing `justify-between` causes no change

2024-09-23 03:15 UTC, geraxrodriguez commented on src/app/ui/directory.tsx
> +      >
noticed that this <div> has a resizing, "jumping" effect that is more noticeable on screen sizes below 768px. 

When you use the filter for an industry that doesn't return any orgs (e.g. "cybersecurity"), the directory resizes down to it's minimum width. Jumps back if you select an industry that returns an org.

Not sure how big of an issue this is, but thought I would mention.

2024-09-23 03:50 UTC, geraxrodriguez requested changes
Left just a couple of comments for you. Nice work homie!

2024-09-23 15:42 UTC, jvmontes commented on src/app/ui/directory.tsx
> +      >
@geraxrodriguez created a new bug and added to the backlog on Asana: https://app.asana.com/0/1207992233793749/1208379370797118/f

2024-09-23 15:53 UTC, merged