Navbar
jvmontes/lpdd pull request #8
Opened 2024-09-13 00:16 UTC by geraxrodriguez

Added styled navbar

Added two more folders for routing. 4 total now (about, contact, placeholder, and login). 

Added LPDD logo.

Tested on mobile and desktop screens. 

Known issues:
- [ ] if more navlinks are added, it would look crammed on mobile. Ideally, we update the design to implement a hamburger menu

2024-09-13 15:44 UTC, jvmontes commented on src/app/ui/nav-bar.tsx
> +
I took a look at this. I see how you were using flex-col to align the items center. I believe I came up with an alternate solution that accomplishes the same objective but cleans up the code a bit. 

Change would be here:

```
  const navClasses = clsx(
    "w-full h-14 flex items-center justify-between px-2 bg-slate-900",
    pathname === "/" && "absolute z-10 bg-transparent"
  );
```

So we combine `flex items-center justify-between` and then just remove a layer (that first div inside the nav)

```
  return (
    <nav className={navClasses}>
      <Link href="/" className="flex items-center mr-12">
        <Image...
```

Let me know what you think about this approach... copied the full component below with changes for additional clarity. 

```
"use client";

import Link from "next/link";
import NavLinks from "./nav-links";
import { usePathname } from "next/navigation";
import clsx from "clsx";
import Image from "next/image";

export default function NavBar() {
  const pathname = usePathname();

  const navClasses = clsx(
    "w-full h-14 flex items-center justify-between px-2 bg-slate-900",
    pathname === "/" && "absolute z-10 bg-transparent"
  );

  return (
    <nav className={navClasses}>
      <Link href="/" className="flex items-center mr-12">
        <Image
          src="/logo.svg"
          width={40}
          height={40}
          alt="Logo for Latiné Professional Development Directory"
        />
        <p className="text-xl text-white tracking-tighter">LPDD</p>
      </Link>
      <NavLinks />
    </nav>
  );
}
```

2024-09-13 15:44 UTC, jvmontes commented on src/app/ui/nav-links.tsx
> +    name: "ABOUT",
be ABOUT it

2024-09-13 15:45 UTC, jvmontes commented on src/app/ui/nav-links.tsx
> +    name: "CONTACT",
if this change was done for styling purposes, we also could `.toUppercase()` the strings we display to ensure they're showing up as expected.

2024-09-13 15:45 UTC, jvmontes commented on src/app/ui/nav-links.tsx
> +    href: "/placeholder",
please remove placeholders

2024-09-13 15:46 UTC, jvmontes commented on src/app/ui/nav-links.tsx
> +  },
let's comment out this object for now until the login functionality is closer to being built out.

2024-09-13 15:46 UTC, jvmontes commented on src/app/ui/nav-links.tsx
> +  const baseClasses = "text-[0.70rem] pr-2 tracking-tighter sm:text-sm sm:pl-8 sm:tracking-normal";
should we remove the `sm` qualifiers and consider running past the designers to find a good `md` option?

2024-09-13 15:49 UTC, jvmontes commented on src/app/ui/nav-links.tsx
> +                isActiveLink ? activeClasses : inactiveClasses
great clean up. well done.

2024-09-13 15:50 UTC, jvmontes commented on src/app/ui/nav-links.tsx
> +          <Link key={name} href={href} className="flex items-center">
I just tested removing `className="flex items-center"` and it looks like it caused no change. Can you test this on your end and if it's not necessary, can we remove it?

2024-09-19 14:58 UTC, geraxrodriguez commented on src/app/ui/home-hero.tsx
> +      <div className="w-full h-full mr-1">
hmm, not sure. Deleted it. Apologies.

2024-09-19 15:12 UTC, geraxrodriguez commented on src/app/ui/nav-bar.tsx
> +    pathname === '/' && "sm:absolute sm:z-10 sm:bg-transparent"
good catch. the first two have been added for all sizes. 

`sm:bg-transparent` needs to stay as is so that the background color shows when on the home page for mobile.

2024-09-19 15:36 UTC, geraxrodriguez commented on src/app/ui/nav-links.tsx
> +    href: "/placeholder",
Removed.

2024-09-19 16:07 UTC, geraxrodriguez commented on src/app/ui/nav-links.tsx
> +          <Link key={name} href={href} className="flex items-center">
No change!! Removed.

2024-09-19 16:09 UTC, geraxrodriguez commented on src/app/ui/nav-links.tsx
> +  const baseClasses = "text-[0.70rem] pr-2 tracking-tighter sm:text-sm sm:pl-8 sm:tracking-normal";
We can. I'll resolve this for now, but will make note of it that we'll be discussing this with designers.

2024-09-21 17:28 UTC, jvmontes requested changes

2024-09-21 17:28 UTC, jvmontes commented on src/app/placeholder/page.tsx
> +export default function Page() {
delete this?

2024-09-21 17:28 UTC, jvmontes commented on src/app/ui/nav-bar.tsx
> +    // "w-full h-14 flex flex-col justify-center bg-slate-900 absolute z-10",
please delete and do not commit commented out code

2024-09-21 17:28 UTC, jvmontes commented on src/app/ui/nav-bar.tsx
> +    // </nav>
please delete commented code

2024-09-21 17:28 UTC, jvmontes commented on src/app/ui/nav-links.tsx
> +// home - about - contact - login
idk if this comment is necessary. ask chat gpt about Clean Code by Uncle Bob & self-documenting code. 

Spoiler alert: answer below


> Ah, yes! Uncle Bob emphasizes the importance of clean code and the idea that code should be self-documenting. This means that well-written code, by itself, should be understandable without needing excessive comments. Here's a quick refresher on the key principles:
> 
> Meaningful Names: Variables, functions, and classes should have names that reveal their intent. This makes the code easier to understand just by reading it.
> 
> Single Responsibility Principle (SRP): Each function or class should do one thing, and do it well. This avoids complex, multi-purpose blocks of code that are hard to follow or modify.
> 
> Avoid Comments: Comments are often redundant if your code is clean and self-explanatory. Instead of commenting on what the code does, write the code clearly enough that the intent is obvious.
> 
> Small Functions: Functions should be short and focused. A good rule is that they should fit on one screen without scrolling.
> 
> Consistent Formatting: Maintain consistent indentation, spacing, and line breaks. This makes the code easier to visually parse and contributes to readability.
> 
> DRY (Don't Repeat Yourself): Avoid duplicating code. If you find the same logic repeated in multiple places, refactor it into a reusable function or class.
> 
> Error Handling: Handle errors in a way that makes the flow of the code still easy to understand.
> 
> These ideas contribute to self-documenting code, where the code is its own explanation. It's readable and makes sense to any developer picking it up, like a well-written book!

2024-09-21 17:28 UTC, jvmontes commented on src/app/ui/nav-links.tsx
> +  // },
im ok with leaving this comment here since it'll hopefully be tackled soon

2024-09-21 17:28 UTC, jvmontes commented on src/app/ui/nav-links.tsx
> +  const baseClasses = "text-[0.70rem] pr-2 tracking-tighter sm:text-sm sm:pl-8 sm:tracking-normal";
preference to use something like text-base, text-sm, text-md, text-lg, etc. over explicit rem values. Please try to find a pre-existing tailwind class that can work, if possible, prefferably.

2024-09-23 16:04 UTC, jvmontes commented on src/app/ui/nav-links.tsx
> +  const baseClasses = "text-[0.70rem] pr-2 tracking-tighter sm:text-sm sm:pl-8 sm:tracking-normal";
I am removing the basClasses const because if these Tailwind Classes aren't in a className attribute, when you hover over them, it doesn't show the actual CSS class tooltip provided by the Tailwind CSS IntelliSense plugin.

2024-09-23 16:05 UTC, jvmontes approved these changes

2024-09-23 16:07 UTC, merged